version: '3'
services:
  web:
    network_mode: host
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT: 12
    depends_on:
        - db
    env_file: ../.env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: localhost
    working_dir: /workspaces
    volumes:
      - ..:/workspaces:cached
    
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    network_mode: host
    image: postgres
    restart: unless-stopped
    env_file: ../.env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  datadog:
    build: datadog
    links:
     - db # ensures that redis is a host that the container can find
     - web # ensures that the web app can send metrics
    environment:
     - DD_API_KEY=7533d872adee3d57c477ffeb87c36d65
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /proc/:/host/proc/:ro
     - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

